# Mock bird.conf for BGP in Cloud

protocol static core_pools {
    route 192.0.2.0/24 blackhole;
    route 2001:db8::/48 blackhole;
}

protocol static advertised_prefixes {
    include "/etc/bird/prefixes.conf";
}

filter route64_export;

function route64_export() {
    if source = "static" then {
        if proto = "core_pools" then {
            accept;
        }
        if proto = "advertised_prefixes" then {
            if dest = RTD_BLACKHOLE then {
                bgp_community.add((212895, 1, 666));
            }
            accept;
        }
    }
    reject;
}
