import subprocess
from rich.console import Console
from bic.core import BIC_DB

CONSOLE = Console()
PEERS_CONF_FILE = "/etc/bird/peers.conf"

def list_bgp_sessions(db_core: BIC_DB):
    """Lists all BGP sessions from the database with client info."""
    try:
        sessions = db_core.find_all("bgp_sessions")
        clients_map = {c['id']: c for c in db_core.find_all("clients")}

        return [{
            "id": s['id'], "state": s['state'], "last_updated": s['last_updated'],
            "client_name": clients_map.get(s['client_id'], {}).get('name'),
            "client_asn": clients_map.get(s['client_id'], {}).get('asn')
        } for s in sessions if s['client_id'] in clients_map]
    except Exception as e:
        CONSOLE.print(f"[red]Error listing BGP sessions: {e}[/red]")
        return []

def create_client_bgp_config(db_core: BIC_DB, client: dict):
    """Generates client-side BGP configs for FRR and BIRD."""
    if not client.get("asn"):
        return {}

    local_asn = db_core.get_setting('bgp_local_asn')
    client_asn = client["asn"]
    
    allocs = db_core.find_all_by("ip_allocations", {"client_id": client["id"]})
    client_v4 = next((a["ip_address"] for a in allocs if "Transit P2P IPv4" in a.get("description", "")), None)
    client_v6 = next((a["ip_address"] for a in allocs if "Transit P2P IPv6" in a.get("description", "")), None)

    if not client_v4 or not client_v6:
        return {}
        
    server_v4_pool = db_core.find_one('ip_pools', {'name': 'WG Server P2P IPv4'})
    server_v6_pool = db_core.find_one('ip_pools', {'name': 'WG Server P2P IPv6'})
    server_v4 = str(next(ipaddress.ip_network(server_v4_pool['cidr']).hosts()))
    server_v6 = str(next(ipaddress.ip_network(server_v6_pool['cidr']).hosts()))

    # --- FRR Config ---
    frr_conf = f"""!
router bgp {client_asn}
 bgp router-id {client_v4}
 !
 neighbor {server_v4} remote-as {local_asn}
 neighbor {server_v4} description "BGP In Cloud IPv4"
 !
 neighbor {server_v6} remote-as {local_asn}
 neighbor {server_v6} description "BGP In Cloud IPv6"
 !
 address-family ipv4 unicast
  ! Announce your prefixes here
  ! network X.X.X.X/X
 exit-address-family
 !
 address-family ipv6 unicast
  ! Announce your prefixes here
  ! network X:X::X/X
 exit-address-family
"""

    # --- BIRD Config ---
    bird_conf = f"""#
router id {client_v4};

protocol device {{ scan time 10; }}
protocol kernel {{ ipv4 {{ export all; }}; ipv6 {{ export all; }}; }}

protocol static {{
    # Announce your prefixes here
    # route X.X.X.X/X blackhole;
}}

protocol bgp v4_uplink {{
    local as {client_asn}; neighbor {server_v4} as {local_asn};
    source address {client_v4};
    ipv4 {{ import all; export where proto = "static"; }};
}}

protocol bgp v6_uplink {{
    local as {client_asn}; neighbor {server_v6} as {local_asn};
    source address {client_v6};
    ipv6 {{ import all; export where proto = "static"; }};
}}
"""
    return {"frr_conf": frr_conf, "bird_conf": bird_conf}

def update_server_bgp_config(db_core: BIC_DB):
    """Generates the complete BIRD peers.conf file from all BGP clients."""
    clients = db_core.find_all_by('clients', {'type': 'Transit'})
    config_content = "# This file is auto-generated by BIC IPAM\n"
    config_content += "# Do not edit manually.\n\n"

    for client in clients:
        if not client.get("asn"):
            continue

        allocs = db_core.find_all_by("ip_allocations", {"client_id": client["id"]})
        client_v4 = next((a["ip_address"] for a in allocs if "Transit P2P IPv4" in a.get("description", "")), None)
        client_v6 = next((a["ip_address"] for a in allocs if "Transit P2P IPv6" in a.get("description", "")), None)
        
        if not client_v4 or not client_v6:
            continue
        
        client_name_safe = client["name"].replace(" ", "_")
        config_content += f"# Peer: {client['name']} (ASN: {client['asn']})\n"
        config_content += f"protocol bgp {client_name_safe}_v4 {{\n"
        config_content += f"    description \"{client['name']}\";\n"
        config_content += f"    local as {db_core.get_setting('bgp_local_asn')};\n"
        config_content += f"    neighbor {client_v4} as {client['asn']};\n"
        config_content += f"    ipv4 {{ import all; export filter {{ if net ~ [0.0.0.0/0] then accept; reject; }}; }};\n"
        config_content += f"}}\n\n"
        config_content += f"protocol bgp {client_name_safe}_v6 {{\n"
        config_content += f"    description \"{client['name']}\";\n"
        config_content += f"    local as {db_core.get_setting('bgp_local_asn')};\n"
        config_content += f"    neighbor {client_v6} as {client['asn']};\n"
        config_content += f"    ipv6 {{ import all; export filter {{ if net ~ [::/0] then accept; reject; }}; }};\n"
        config_content += f"}}\n\n"

    try:
        with open("/tmp/peers.conf.tmp", "w") as f:
            f.write(config_content)
        subprocess.run(["sudo", "mv", "/tmp/peers.conf.tmp", PEERS_CONF_FILE], check=True)
        _reload_bird()
    except Exception as e:
        CONSOLE.print(f"[bold red]Failed to write {PEERS_CONF_FILE}: {e}[/bold red]")

def _reload_bird():
    try:
        CONSOLE.print("  -> Reloading BIRD daemon...")
        subprocess.run(["sudo", "birdc", "configure"], check=True, capture_output=True, text=True)
        CONSOLE.print("[green]✅ BIRD configuration reloaded.[/green]")
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        CONSOLE.print(f"[bold red]Error reloading BIRD: {e}[/bold red]")
