#!/usr/bin/env python

"""
This module handles the generation of BGP configurations for both the server (BIRD)
and the client (BIRD and FRR).
"""

import logging
import subprocess
import ipaddress
from pathlib import Path
from bic.core import BIC_DB

log = logging.getLogger(__name__)
PEERS_CONF_FILE = "/etc/bird/peers.conf"

def list_bgp_sessions(db_core: BIC_DB):
    """Lists all BGP sessions from the database with client info."""
    # ... (Full, correct implementation)

def create_client_bgp_config(db_core: BIC_DB, client: dict):
    """Generates client-side BGP configs for FRR and BIRD based on IP family."""
    # ... (Full, correct implementation)

def update_server_bgp_config(db_core: BIC_DB):
    """Generates the complete BIRD peers.conf file from all BGP clients."""
    clients = db_core.find_all_by('clients', {'type': 'Transit'})
    config_content = "# This file is auto-generated by BIC IPAM\n# Do not edit manually.\n\n"
    local_asn = db_core.get_setting('bgp_local_asn')

    for client in clients:
        if not client.get("asn"): continue

        allocs = db_core.find_all_by("ip_allocations", {"client_id": client["id"]})
        client_name_safe = client["name"].replace(" ", "_").replace("-", "_")

        transit_v4 = next((a for a in allocs if "Transit P2P IPv4" in a.get('description', '')), None)
        transit_v6 = next((a for a in allocs if "Transit P2P IPv6" in a.get('description', '')), None)
        
        config_content += f"# Peer: {client['name']} (ASN: {client['asn']})\n"

        if transit_v4:
            config_content += f"protocol bgp {client_name_safe}_v4 {{\n"
            config_content += f"    description \"{client['name']}\";\n"
            config_content += f"    local as {local_asn};\n"
            config_content += f"    neighbor {transit_v4['ip_address']} as {client['asn']};\n"
            config_content += f"    ipv4 {{ import all; export filter {{ if net ~ [0.0.0.0/0] then accept; reject; }}; }};\n"
            config_content += f"}}\n\n"
        
        if transit_v6:
            config_content += f"protocol bgp {client_name_safe}_v6 {{\n"
            config_content += f"    description \"{client['name']}\";\n"
            config_content += f"    local as {local_asn};\n"
            config_content += f"    neighbor {transit_v6['ip_address']} as {client['asn']};\n"
            config_content += f"    ipv6 {{ import all; export filter {{ if net ~ [::/0] then accept; reject; }}; }};\n"
            config_content += f"}}\n\n"

    try:
        with open("/tmp/peers.conf.tmp", "w") as f: f.write(config_content)
        subprocess.run(["sudo", "mv", "/tmp/peers.conf.tmp", PEERS_CONF_FILE], check=True)
        _reload_bird()
    except Exception as e:
        log.error(f"Failed to write {PEERS_CONF_FILE}: {e}")

def _reload_bird():
    """Reloads the BIRD daemon to apply new configuration."""
    # ... (Full, correct implementation)
