import ipaddress
import subprocess
from rich.console import Console
from bic.core import BIC_DB

console = Console()

BIRD_EXPORT_FILE_V4 = "/etc/bird/bic_export_prefixes_v4.conf"
BIRD_EXPORT_FILE_V6 = "/etc/bird/bic_export_prefixes_v6.conf"

def update_bird_export_config(db_core: BIC_DB):
    """Generates BIRD config files for IPv4 and IPv6 public prefixes."""
    console.print("\n[cyan]Updating BIRD export configuration...[/cyan]")
    try:
        pools = db_core.find_all("ip_pools")
        v4_cidrs = []
        v6_cidrs = []

        for pool in pools:
            try:
                net = ipaddress.ip_network(pool['cidr'])
                if not net.is_private:
                    if net.version == 4:
                        v4_cidrs.append(net)
                    else:
                        v6_cidrs.append(net)
            except ValueError:
                continue # Ignore invalid CIDRs in the database

        # Generate and write IPv4 config
        _write_bird_config(BIRD_EXPORT_FILE_V4, v4_cidrs, 4)

        # Generate and write IPv6 config
        _write_bird_config(BIRD_EXPORT_FILE_V6, v6_cidrs, 6)

        # Reload BIRD to apply changes
        console.print("   -> Reloading BIRD daemon...")
        subprocess.run(["sudo", "birdc", "configure"], check=True, capture_output=True, text=True)
        console.print("[green]✅ BIRD configuration updated and reloaded successfully.[/green]")

    except FileNotFoundError:
        console.print(f"[bold red]Error: 'sudo' command not found. Cannot update BIRD.[/bold red]")
    except subprocess.CalledProcessError as e:
        console.print(f"[bold red]Error reloading BIRD:[/bold red]")
        console.print(f"[red]STDOUT: {e.stdout}[/red]")
        console.print(f"[red]STDERR: {e.stderr}[/red]")
    except Exception as e:
        console.print(f"[bold red]An unexpected error occurred: {e}[/bold red]")

def _write_bird_config(filename, cidrs, version):
    content = f"# This file is automatically generated by the BIC IPAM system for IPv{version}.\n"
    content += "# Do not edit manually.\n\n"
    content += f"define BIC_EXPORT_PREFIXES_V{version} = [\n"
    if cidrs:
        content += ",\n".join([f"    {str(c)}" for c in cidrs])
    content += "\n];\n"

    temp_file_path = f"/tmp/bic_export_v{version}.tmp"
    with open(temp_file_path, "w") as f:
        f.write(content)
    
    subprocess.run(["sudo", "mv", temp_file_path, filename], check=True)
    subprocess.run(["sudo", "chown", "bird:bird", filename], check=True)

def get_next_available_ip_in_pool(db_core: BIC_DB, pool_id: int):
    pool = db_core.find_one_by('ip_pools', {'id': pool_id})
    if not pool:
        return None, None

    network = ipaddress.ip_network(pool['cidr'])
    allocated_ips_rows = db_core.find_all_by('ip_allocations', {'pool_id': pool_id})
    allocated_ips = {ipaddress.ip_address(row['ip_address']) for row in allocated_ips_rows}

    for ip in network.hosts():
        if ip not in allocated_ips:
            ip_str = str(ip)
            alloc_id = db_core.insert('ip_allocations', {'pool_id': pool_id, 'ip_address': ip_str})
            return ip_str, alloc_id
    return None, None

def add_pool(db_core: BIC_DB, name: str, cidr: str, description: str):
    """Adds a new IP pool to the database after validation."""
    try:
        net = ipaddress.ip_network(cidr)
        afi = f"ipv{net.version}"
    except ValueError:
        return {"success": False, "message": "Invalid CIDR notation."}

    db_core.insert('ip_pools', {
        'name': name,
        'afi': afi,
        'cidr': cidr,
        'description': description
    })
    # After adding a public pool, BIRD config should be updated
    update_bird_export_config(db_core)
    return {"success": True, "message": f"IP Pool '{name}' ({cidr}) created successfully."}

def delete_pool(db_core: BIC_DB, pool_id: int):
    """Deletes an IP pool after checking for active allocations."""
    # Check for any IPs in this pool that are assigned to a client
    allocations = db_core.find_all_by('ip_allocations', {'pool_id': pool_id})
    active_allocations = [a for a in allocations if a['client_id'] is not None]

    if active_allocations:
        return {"success": False, "message": f"Cannot delete pool. It has {len(active_allocations)} active IP allocation(s)."}

    # If we are here, no IPs are actively assigned. We can proceed.
    pool = db_core.find_one_by('ip_pools', {'id': pool_id})
    pool_name = pool['name']

    # Delete all placeholder allocations for this pool
    for alloc in allocations:
        db_core.delete('ip_allocations', alloc['id'])

    # Delete the pool itself
    db_core.delete('ip_pools', pool_id)

    # After deleting a public pool, BIRD config should be updated
    update_bird_export_config(db_core)

    return {"success": True, "message": f"IP Pool '{pool_name}' and its {len(allocations)} placeholder allocation(s) have been deleted."}

def get_next_available_ip_in_pool_by_name(db_core: BIC_DB, pool_name: str):
    pool = db_core.find_one_by('ip_pools', {'name': pool_name})
    if not pool:
        return None, None
    return get_next_available_ip_in_pool(db_core, pool['id'])

def get_next_available_asn(db_core: BIC_DB):
    used_asns = {res['asn'] for res in db_core.find_all('clients') if res['asn']}
    for asn in range(64512, 65535):
        if asn not in used_asns:
            return asn
    return None

def deallocate_ip(db_core: BIC_DB, allocation_id: int):
    db_core.update('ip_allocations', allocation_id, {'client_id': None})

    return {"success": True, "message": f"IP Pool '{pool_name}' and its {len(allocations)} placeholder allocation(s) have been deleted."}

def swap_pool_prefix(db_core: BIC_DB, pool_id: int, new_cidr: str):
    """Remaps all allocated IPs within a pool to a new CIDR block."""
    try:
        new_network = ipaddress.ip_network(new_cidr)
    except ValueError:
        return {"success": False, "message": "Invalid new CIDR notation."}

    pool = db_core.find_one_by('ip_pools', {'id': pool_id})
    if not pool:
        return {"success": False, "message": "Pool not found."}

    try:
        old_network = ipaddress.ip_network(pool['cidr'])
    except ValueError:
        return {"success": False, "message": "The existing pool has an invalid CIDR, cannot perform swap."}

    if old_network.num_addresses != new_network.num_addresses:
        return {"success": False, "message": "Prefix swap is only supported between networks of the same size."}

    allocations = db_core.find_all_by('ip_allocations', {'pool_id': pool_id})
    
    console.print(f"Remapping {len(allocations)} IP(s) from {old_network} to {new_network}...")
    
    for alloc in allocations:
        old_ip = ipaddress.ip_address(alloc['ip_address'])
        # Calculate the host's position in the old network
        # This is a simplification; direct integer arithmetic on IPs is better
        offset = int(old_ip) - int(old_network.network_address)
        new_ip = new_network.network_address + offset

        db_core.update('ip_allocations', alloc['id'], {'ip_address': str(new_ip)})
        console.print(f"  -> {old_ip} -> {new_ip}")

    # Finally, update the pool's CIDR
    db_core.update('ip_pools', pool_id, {'cidr': new_cidr})
    
    # After swapping a public pool, BIRD config should be updated
    update_bird_export_config(db_core)

    return {"success": True, "message": f"Successfully swapped prefix for pool '{pool['name']}'."}


def find_and_allocate_subnet(db_core: BIC_DB, pool_id: int, prefix_length: int):
    pool = db_core.find_one_by('ip_pools', {'id': pool_id})
    if not pool:
        return None, None

    try:
        parent_network = ipaddress.ip_network(pool['cidr'])
    except ValueError:
        return None, None # Invalid CIDR in database

    existing_allocations = db_core.find_all_by('ip_allocations', {'pool_id': pool_id})
    existing_subnets = db_core.find_all_by('ip_subnets', {'pool_id': pool_id})

    allocated_ips = {ipaddress.ip_address(alloc['ip_address']) for alloc in existing_allocations}
    allocated_subnets = {ipaddress.ip_network(sub['subnet']) for sub in existing_subnets}

    for potential_subnet in parent_network.subnets(new_prefix=prefix_length):
        is_available = True
        if any(potential_subnet.overlaps(existing) for existing in allocated_subnets):
            is_available = False
            continue

        for ip in allocated_ips:
            if ip in potential_subnet:
                is_available = False
                break
        
        if is_available:
            subnet_str = str(potential_subnet)
            description = f"Allocated from {pool['name']} for prefix length {prefix_length}"
            subnet_id = db_core.insert('ip_subnets', {
                'pool_id': pool_id,
                'subnet': subnet_str,
                'description': description
            })
            return subnet_str, subnet_id

    return None, None