import subprocess
import os
from rich.console import Console
from bic.core import BIC_DB
import ipaddress

console = Console()

WG_CONF_DIR = "/etc/wireguard/"
BIC_CLIENT_CONF_DIR = os.path.join(os.path.expanduser("~"), ".bic", "client_confs")

def generate_keys():
    """Generates a new WireGuard private and public key pair."""
    try:
        privkey = subprocess.check_output("wg genkey", shell=True, text=True).strip()
        pubkey = subprocess.check_output(f'echo "{privkey}" | wg pubkey', shell=True, text=True).strip()
        return {"private_key": privkey, "public_key": pubkey}
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        console.print(f"[bold red]Error using 'wg' command: {e}. Is WireGuard installed?[/bold red]")
        return None

def write_server_config_from_db(db_core: BIC_DB, interface_id: int):
    """Writes a WireGuard server config file based on DB state."""
    interface = db_core.find_one('wireguard_interfaces', {'id': interface_id})
    if not interface:
        return None

    conf_path = os.path.join(WG_CONF_DIR, f"{interface['name']}.conf")
    content = f"# Auto-generated by BIC IPAM for {interface['name']}\n"
    content += "[Interface]\n"
    content += f"Address = {interface['address']}\n"
    content += f"ListenPort = {interface['listen_port']}\n"
    content += f"PrivateKey = {interface['private_key']}\n"

    peers = db_core.find_all_by('wireguard_peers', {'interface_id': interface_id})
    for peer in peers:
        content += f"\n# Peer: {peer['name']}\n"
        content += "[Peer]\n"
        content += f"PublicKey = {peer['public_key']}\n"
        content += f"AllowedIPs = {peer['allowed_ips']}\n"

    try:
        # Write to a temp file and then move with sudo
        temp_path = f"/tmp/{interface['name']}.conf.tmp"
        with open(temp_path, 'w') as f:
            f.write(content)
        subprocess.run(["sudo", "mv", temp_path, conf_path], check=True)
        subprocess.run(["sudo", "chown", "root:root", conf_path], check=True)
        subprocess.run(["sudo", "chmod", "600", conf_path], check=True)
        return conf_path
    except Exception as e:
        console.print(f"[bold red]Failed to write WireGuard config {conf_path}: {e}[/bold red]")
        return None

def update_wireguard_config_for_client(db_core: BIC_DB, client_id: int):
    """The single source of truth for creating and updating a client's WireGuard config."""
    client = db_core.find_one("clients", {"id": client_id})
    if not client:
        return {"success": False, "message": "Client not found."}

    server_interface = ensure_server_interface(db_core)
    if not server_interface:
        return {"success": False, "message": "Could not ensure WireGuard server interface."}

    # Calculate AllowedIPs
    single_ips = db_core.find_all_by('ip_allocations', {'client_id': client_id})
    subnets = db_core.find_all_by('ip_subnets', {'client_id': client_id})
    allowed_ips_list = [f"{alloc['ip_address']}/{128 if ':' in alloc['ip_address'] else 32}" for alloc in single_ips]
    allowed_ips_list.extend([s['subnet'] for s in subnets])
    allowed_ips_str = ", ".join(allowed_ips_list)

    # Find or create peer
    peer = db_core.find_one('wireguard_peers', {'client_id': client_id})
    if peer:
        # Update existing peer
        db_core.update('wireguard_peers', peer['id'], {'allowed_ips': allowed_ips_str})
        client_private_key = db_core.get_setting(f"wg_client_{client_id}_privkey") # Assumes we store this
    else:
        # Create new peer
        keys = generate_keys()
        if not keys:
            return {"success": False, "message": "Failed to generate WireGuard keys."}
        
        peer_id = db_core.insert('wireguard_peers', {
            'interface_id': server_interface['id'],
            'client_id': client_id,
            'name': client['name'],
            'public_key': keys['public_key'],
            'allowed_ips': allowed_ips_str,
        })
        client_private_key = keys['private_key']
        # Store the private key securely
        db_core.insert_or_replace('settings', {'key': f"wg_client_{client_id}_privkey", 'value': client_private_key})

    # Generate client config content
    all_settings = {s['key']: s['value'] for s in db_core.find_all('settings')}
    dns_v4 = all_settings.get('dns_server_ipv4', '1.1.1.1')
    dns_v6 = all_settings.get('dns_server_ipv6', '2606:4700:4700::1111')
    wg_endpoint = all_settings.get('wg_server_endpoint', 'your-server.example.com')
    client_p2p_ips = [f"{alloc['ip_address']}/{128 if ':' in alloc['ip_address'] else 32}" for alloc in single_ips if 'P2P' in alloc.get('description', '')]

    client_conf = "[Interface]\n"
    client_conf += f"PrivateKey = {client_private_key}\n"
    client_conf += f"Address = {', '.join(client_p2p_ips)}\n"
    client_conf += f"DNS = {dns_v4}, {dns_v6}\n\n"
    client_conf += "[Peer]\n"
    client_conf += f"PublicKey = {server_interface['public_key']}\n"
    client_conf += f"Endpoint = {wg_endpoint}:{server_interface['listen_port']}\n"
    client_conf += "AllowedIPs = 0.0.0.0/0, ::/0\n"
    client_conf += "PersistentKeepalive = 25\n"

    db_core.update('clients', client_id, {'wireguard_conf': client_conf})

    # Rewrite the server config to add/update the peer
    write_server_config_from_db(db_core, server_interface['id'])
    
    return {"success": True, "message": "WireGuard configuration updated."}

def remove_peer_from_interface(db_core: BIC_DB, peer_id: int):
    """Removes a peer from the DB and rewrites the server config."""
    peer = db_core.find_one('wireguard_peers', {'id': peer_id})
    if not peer:
        return False
    
    interface_id = peer['interface_id']
    db_core.delete('wireguard_peers', peer_id)

    # Rewrite the server config to remove the peer
    write_server_config_from_db(db_core, interface_id)
    return True

def ensure_server_interface(db_core: BIC_DB):
    """Ensures the primary wg1 server interface exists in the DB, creating if not."""
    interface = db_core.find_one('wireguard_interfaces', {'name': 'wg1'})
    if interface:
        return interface
    
    console.print("[cyan]Primary WireGuard interface 'wg1' not found in DB, creating...[/cyan]")
    keys = generate_keys()
    if not keys:
        return None

    # Get server P2P addresses from the special pools
    v4_pool = db_core.find_one('ip_pools', {'name': 'WG Server P2P IPv4'})
    v6_pool = db_core.find_one('ip_pools', {'name': 'WG Server P2P IPv6'})
    
    v4_net = ipaddress.ip_network(v4_pool['cidr'])
    v6_net = ipaddress.ip_network(v6_pool['cidr'])
    
    server_v4 = v4_net.network_address + 1
    server_v6 = v6_net.network_address + 1

    interface_id = db_core.insert('wireguard_interfaces', {
        'name': 'wg1',
        'listen_port': 51821, # Your specified port
        'address': f"{server_v4}/{v4_net.prefixlen}, {server_v6}/{v6_net.prefixlen}",
        'private_key': keys['private_key'],
        'public_key': keys['public_key']
    })
    return db_core.find_one('wireguard_interfaces', {'id': interface_id})

def rebuild_and_update_peer_allowed_ips(db_core: BIC_DB, client_id: int):
    """Recalculates a client's AllowedIPs and updates the WG config."""
    # This function is now superseded by update_wireguard_config_for_client
    return update_wireguard_config_for_client(db_core, client_id)

def list_peers_joined(db_core: BIC_DB):
    """Lists all WireGuard peers with client and interface info."""
    query = """
        SELECT
            p.id, p.name, p.public_key, p.allowed_ips,
            c.name as client_name,
            i.name as interface_name
        FROM wireguard_peers p
        LEFT JOIN clients c ON p.client_id = c.id
        LEFT JOIN wireguard_interfaces i ON p.interface_id = i.id
    """
    rows = db_core.conn.execute(query).fetchall()
    return [dict(row) for row in rows]
