import subprocess
import os
from rich.console import Console
from bic.core import BIC_DB, get_wan_interface, get_wan_ip
import ipaddress

console = Console()

WG_CONF_DIR = "/etc/wireguard/"
BIC_CLIENT_CONF_DIR = os.path.join(os.path.expanduser("~"), ".bic", "client_confs")

def generate_keys():
    """Generates a new WireGuard private and public key pair."""
    try:
        privkey = subprocess.check_output("wg genkey", shell=True, text=True).strip()
        pubkey = subprocess.check_output(f'echo "{privkey}" | wg pubkey', shell=True, text=True).strip()
        return {"private_key": privkey, "public_key": pubkey}
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        console.print(f"[bold red]Error using 'wg' command: {e}. Is WireGuard installed?[/bold red]")
        return None

def write_server_config_from_db(db_core: BIC_DB, interface_id: int):
    """Writes a WireGuard server config file based on DB state."""
    interface = db_core.find_one('wireguard_interfaces', {'id': interface_id})
    if not interface:
        return None

    wan_interface = get_wan_interface()
    conf_path = os.path.join(WG_CONF_DIR, f"{interface['name']}.conf")
    content = f"# Auto-generated by BIC IPAM for {interface['name']}\n"
    content += "[Interface]\n"
    content += f"Address = {interface['address']}\n"
    content += f"ListenPort = {interface['listen_port']}\n"
    content += f"PrivateKey = {interface['private_key']}\n"
    content += "MTU = 1420\n"
    content += "PostUp = sysctl -w net.ipv4.ip_forward=1\n"
    content += "PostUp = sysctl -w net.ipv6.conf.all.forwarding=1\n"
    content += f"PostUp = iptables -t nat -A POSTROUTING -s 172.30.0.0/24 -o {wan_interface} -j MASQUERADE\n"
    content += f"PostDown = iptables -t nat -D POSTROUTING -s 172.30.0.0/24 -o {wan_interface} -j MASQUERADE\n"

    peers = db_core.find_all_by('wireguard_peers', {'interface_id': interface_id})
    for peer in peers:
        content += f"\n# Peer: {peer['name']}\n"
        content += "[Peer]\n"
        content += f"PublicKey = {peer['public_key']}\n"
        content += f"AllowedIPs = {peer['allowed_ips']}\n"

    try:
        temp_path = f"/tmp/{interface['name']}.conf.tmp"
        with open(temp_path, 'w') as f:
            f.write(content)
        subprocess.run(["sudo", "mv", temp_path, conf_path], check=True)
        subprocess.run(["sudo", "chown", "root:root", conf_path], check=True)
        subprocess.run(["sudo", "chmod", "600", conf_path], check=True)
        return conf_path
    except Exception as e:
        console.print(f"[bold red]Failed to write WireGuard config {conf_path}: {e}[/bold red]")
        return None

def update_wireguard_config_for_client(db_core: BIC_DB, client_id: int):
    """The single source of truth for creating and updating a client's WireGuard config."""
    client = db_core.find_one("clients", {"id": client_id})
    if not client:
        return {"success": False, "message": "Client not found."}

    server_interface = ensure_server_interface(db_core)
    if not server_interface:
        return {"success": False, "message": "Could not ensure WireGuard server interface."}

    # --- IP Analysis ---
    allocations = db_core.find_all_by('ip_allocations', {'client_id': client_id})
    subnets = db_core.find_all_by('ip_subnets', {'client_id': client_id})

    has_ipv4 = any(ipaddress.ip_address(a['ip_address']).version == 4 for a in allocations) or \
               any(ipaddress.ip_network(s['subnet']).version == 4 for s in subnets)
    has_ipv6 = any(ipaddress.ip_address(a['ip_address']).version == 6 for a in allocations) or \
               any(ipaddress.ip_network(s['subnet']).version == 6 for s in subnets)

    transit_v4 = next((a for a in allocations if "Transit P2P IPv4" in a.get('description', '')), None)
    transit_v6 = next((a for a in allocations if "Transit P2P IPv6" in a.get('description', '')), None)
    direct_ips = [a for a in allocations if "Transit" not in a.get('description', '')]

    # --- Server-Side Peer Config ---
    server_allowed_ips = []
    if has_ipv4 and transit_v4: server_allowed_ips.append(f"{transit_v4['ip_address']}/32")
    if has_ipv6 and transit_v6: server_allowed_ips.append(f"{transit_v6['ip_address']}/128")
    if client['type'] != 'BGP': # For direct clients, add their public IPs
        server_allowed_ips.extend([f"{a['ip_address']}/{32 if ipaddress.ip_address(a['ip_address']).version == 4 else 128}" for a in direct_ips])
        server_allowed_ips.extend([s['subnet'] for s in subnets])

    # Find or create peer
    peer = db_core.find_one('wireguard_peers', {'client_id': client_id})
    if peer:
        db_core.update('wireguard_peers', peer['id'], {'allowed_ips': ", ".join(server_allowed_ips)})
        client_private_key = db_core.get_setting(f"wg_client_{client_id}_privkey")
    else:
        keys = generate_keys()
        if not keys: return {"success": False, "message": "Failed to generate WireGuard keys."}
        db_core.insert('wireguard_peers', {
            'interface_id': server_interface['id'], 'client_id': client_id, 'name': client['name'],
            'public_key': keys['public_key'], 'allowed_ips': ", ".join(server_allowed_ips),
        })
        client_private_key = keys['private_key']
        db_core.insert_or_replace('settings', {'key': f"wg_client_{client_id}_privkey", 'value': client_private_key})

    # --- Client-Side Config Generation ---
    # DNS
    dns_servers = []
    server_v4_ip = ipaddress.ip_network(server_interface['address'].split(',')[0].strip()).network_address + 1
    server_v6_ip = ipaddress.ip_network(server_interface['address'].split(',')[1].strip()).network_address + 1
    if has_ipv4: dns_servers.append(str(server_v4_ip))
    if has_ipv6: dns_servers.append(str(server_v6_ip))

    # Client-side Address
    client_address_list = []
    if has_ipv4 and transit_v4: client_address_list.append(f"{transit_v4['ip_address']}/32")
    if has_ipv6 and transit_v6: client_address_list.append(f"{transit_v6['ip_address']}/128")
    if client['type'] != 'BGP':
        client_address_list.extend([f"{a['ip_address']}/{32 if ipaddress.ip_address(a['ip_address']).version == 4 else 128}" for a in direct_ips])
        client_address_list.extend([s['subnet'] for s in subnets])

    # Client-side AllowedIPs
    client_allowed_ips = []
    if client['type'] == 'BGP':
        if has_ipv4: client_allowed_ips.append(f"{server_v4_ip}/32")
        if has_ipv6: client_allowed_ips.append(f"{server_v6_ip}/128")
    if has_ipv4: client_allowed_ips.append("0.0.0.0/0")
    if has_ipv6: client_allowed_ips.append("::/0")
    
    # Build the config file
    client_conf = "[Interface]\n"
    client_conf += f"PrivateKey = {client_private_key}\n"
    client_conf += f"Address = {', '.join(client_address_list)}\n"
    client_conf += f"DNS = {', '.join(dns_servers)}\n"
    client_conf += "MTU = 1420\n\n"
    client_conf += "[Peer]\n"
    client_conf += f"PublicKey = {server_interface['public_key']}\n"
    wg_endpoint = db_core.get_setting('wg_server_endpoint') or get_wan_ip() or "127.0.0.1"
    client_conf += f"Endpoint = {wg_endpoint}:{server_interface['listen_port']}\n"
    client_conf += f"AllowedIPs = {', '.join(client_allowed_ips)}\n"
    client_conf += "PersistentKeepalive = 25\n"

    db_core.update('clients', client_id, {'wireguard_conf': client_conf})
    write_server_config_from_db(db_core, server_interface['id'])
    
    return {"success": True, "message": "WireGuard configuration updated."}

def remove_peer_from_interface(db_core: BIC_DB, peer_id: int):
    """Removes a peer from the DB and rewrites the server config."""
    peer = db_core.find_one('wireguard_peers', {'id': peer_id})
    if not peer: return False
    interface_id = peer['interface_id']
    db_core.delete('wireguard_peers', peer_id)
    write_server_config_from_db(db_core, interface_id)
    return True

def ensure_server_interface(db_core: BIC_DB):
    """Ensures the primary wg1 server interface exists in the DB, creating if not."""
    interface = db_core.find_one('wireguard_interfaces', {'name': 'wg1'})
    if interface: return interface
    
    console.print("[cyan]Primary WireGuard interface 'wg1' not found in DB, creating...[/cyan]")
    keys = generate_keys()
    if not keys: return None

    v4_pool = db_core.find_one('ip_pools', {'name': 'WG Server P2P IPv4'})
    v6_pool = db_core.find_one('ip_pools', {'name': 'WG Server P2P IPv6'})
    
    v4_net = ipaddress.ip_network(v4_pool['cidr'])
    v6_net = ipaddress.ip_network(v6_pool['cidr'])
    
    server_v4 = v4_net.network_address + 1
    server_v6 = v6_net.network_address + 1

    interface_id = db_core.insert('wireguard_interfaces', {
        'name': 'wg1', 'listen_port': 51821,
        'address': f"{server_v4}/{v4_net.prefixlen}, {server_v6}/{v6_net.prefixlen}",
        'private_key': keys['private_key'], 'public_key': keys['public_key']
    })
    return db_core.find_one('wireguard_interfaces', {'id': interface_id})
